/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BsButton: typeof import('bts-vue/es/components/bs-button')['default']
    BsDrawer: typeof import('bts-vue/es/components/bs-drawer')['default']
    BsDropdown: typeof import('bts-vue/es/components/bs-dropdown')['default']
    BsDropdownItem: typeof import('bts-vue/es/components/bs-dropdown/widgets/BsDropdownItem')['default']
    BsFormItem: typeof import('bts-vue/es/components/bs-form/widgets/BsFormItem')['default']
    BsMenu: typeof import('bts-vue/es/components/bs-menu')['default']
    BsMenuItem: typeof import('bts-vue/es/components/bs-menu/widgets/BsMenuItem')['default']
    BsMenuItemGroup: typeof import('bts-vue/es/components/bs-menu/widgets/BsMenuItemGroup')['default']
    BsModal: typeof import('bts-vue/es/components/bs-modal')['default']
    BsRadio: typeof import('bts-vue/es/components/bs-radio')['default']
    BsRadioGroup: typeof import('bts-vue/es/components/bs-radio-group')['default']
    BsTooltip: typeof import('bts-vue/es/components/bs-tooltip')['default']
    BsVueDoc: typeof import('./src/components/BsVueDoc.vue')['default']
    ComponentDoc: typeof import('./src/components/ComponentDoc.vue')['default']
    DemoBox: typeof import('./src/components/DemoBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
